[[headers]]
  for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"

# United State
[[redirects]]
from = "/"
to = "/us/"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/transactional-sms"
to = "/us/transactional-sms"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/shorturl"
to = "/us/shorturl"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/transactional-email"
to = "/us/transactional-email"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/rich-communication-services"
to = "/us/rich-communication-services"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/voice-call-api"
to = "/us/voice-call-api"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/whatsapp"
to = "/us/whatsapp"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/one-api"
to = "/us/one-api"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/segmento"
to = "/us/segmento"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/sms-campaign"
to = "/us/sms-campaign"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/hello"
to = "/us/hello"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/send-otp"
to = "/us/send-otp"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/virtual-number"
to = "/us/virtual-number"
status = 301
force = true
conditions = {Country = ["us"]}
[[redirects]]
from = "/internet-messaging"
to = "/us/internet-messaging"
status = 301
force = true
conditions = {Country = ["us"]}

# Spain
[[redirects]]
from = "/"
to = "/es/"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/transactional-sms"
to = "/es/transactional-sms"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/shorturl"
to = "/es/shorturl"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/transactional-email"
to = "/es/transactional-email"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/rich-communication-services"
to = "/es/rich-communication-services"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/voice-call-api"
to = "/es/voice-call-api"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/whatsapp"
to = "/es/whatsapp"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/one-api"
to = "/es/one-api"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/segmento"
to = "/es/segmento"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/sms-campaign"
to = "/es/sms-campaign"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/hello"
to = "/es/hello"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/send-otp"
to = "/es/send-otp"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/virtual-number"
to = "/es/virtual-number"
status = 301
force = true
conditions = {Country = ["es"]}
[[redirects]]
from = "/internet-messaging"
to = "/es/internet-messaging"
status = 301
force = true
conditions = {Country = ["es"]}

# Philippines
[[redirects]]
from = "/"
to = "/ph/"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/transactional-sms"
to = "/ph/transactional-sms"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/shorturl"
to = "/ph/shorturl"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/transactional-email"
to = "/ph/transactional-email"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/rich-communication-services"
to = "/ph/rich-communication-services"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/voice-call-api"
to = "/ph/voice-call-api"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/whatsapp"
to = "/ph/whatsapp"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/one-api"
to = "/ph/one-api"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/segmento"
to = "/ph/segmento"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/sms-campaign"
to = "/ph/sms-campaign"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/hello"
to = "/ph/hello"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/send-otp"
to = "/ph/send-otp"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/virtual-number"
to = "/ph/virtual-number"
status = 301
force = true
conditions = {Country = ["ph"]}
[[redirects]]
from = "/internet-messaging"
to = "/ph/internet-messaging"
status = 301
force = true
conditions = {Country = ["ph"]}

#Singapore
[[redirects]]
from = "/"
to = "/sg/"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/transactional-sms"
to = "/sg/transactional-sms"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/shorturl"
to = "/sg/shorturl"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/transactional-email"
to = "/sg/transactional-email"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/rich-communication-services"
to = "/sg/rich-communication-services"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/voice-call-api"
to = "/sg/voice-call-api"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/whatsapp"
to = "/sg/whatsapp"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/one-api"
to = "/sg/one-api"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/segmento"
to = "/sg/segmento"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/sms-campaign"
to = "/sg/sms-campaign"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/hello"
to = "/sg/hello"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/send-otp"
to = "/sg/send-otp"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/virtual-number"
to = "/sg/virtual-number"
status = 301
force = true
conditions = {Country = ["sg"]}
[[redirects]]
from = "/internet-messaging"
to = "/sg/internet-messaging"
status = 301
force = true
conditions = {Country = ["sg"]}