[[headers]]
  for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"

# [[redirects]]
#   from = ["/", "/hello/", "/segmento/", "/sms-campaign", "send-otp"]
#   to = "/us/:*"
#   status = 301
#   force = true
#   conditions = {Country = ["us"]}